enhance: optimize tiles & hus

diff --git a/tiles-repo/go-bumblebee-jazz/0.7.1/tile-spec.yaml b/tiles-repo/go-bumblebee-jazz/0.7.1/tile-spec.yaml
--- a/tiles-repo/go-bumblebee-jazz/0.7.1/tile-spec.yaml
+++ b/tiles-repo/go-bumblebee-jazz/0.7.1/tile-spec.yaml
@@ -4,7 +4,7 @@ metadata:
     name: Go-Bumblebee-Jazz
     category: Application
     version: 0.7.1
-    dependentOnVendorService: EKS
+    
 spec:
   global:
     env:
@@ -28,36 +28,37 @@ spec:
           curl -H "Authorization: token $GIT_ACCESS_TOKEN" --data '{"name":"'$APP_CONF_REPO'", "private": true}' https://api.github.com/user/repos
         readinessProbe:
           command: |
-            retcode=`curl -s -o /dev/null -w "%{http_code}" https://github.com/$GITHUB_USER/$APP_CONF_REPO`
+            retcode=`curl -H "Authorization: token $GIT_ACCESS_TOKEN" -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/$GITHUB_USER/$APP_CONF_REPO`
             if [ $retcode -ne 200 ]
             then
-              echo 'failed to create repo" >&2
+              echo "failed to create repo"
               exit 1
             fi
+            echo "$APP_CONF_REPO is ready to go!"
           initialDelaySeconds: 5
           periodSeconds: 5
-          timeoutSeconds: 30
+          timeoutSeconds: 300
           successThreshold: 1
-          failureThreshold: 1
+          failureThreshold: -1
       - name: PrepareAppContent
         command: |
           cd $TILE_HOME
-          git clone https://github.com/$GITHUB_USER/$APP_REPO.git
+          rm -rf $APP_REPO;git clone https://github.com/$GITHUB_USER/$APP_REPO.git
           cd $APP_REPO
           git checkout $APP_BRANCH
           git pull
           prod_redis_endpoint=$(self.inputs.prodRedisEndpoint)
-          if [ $prod_redis_endpoint = "" ]
+          if [ $prod_redis_endpoint != "" ]
           then 
-            cd manifest/kustomize/prod/air
+            cd manifests/kustomize/production/air
             sed -i -e 's/redis-cart:6379/'$prod_redis_endpoint'/g' air-deployment.yaml
           fi
       - name: SyncAppContentToRepository
         command: |
           cd $TILE_HOME
-          git clone https://$GIT_ACCESS_TOKEN:x-oauth-basic@github.com/$GITHUB_USER/$APP_CONF_REPO.git
+          rm -rf APP_CONF_REPO;git clone https://$GIT_ACCESS_TOKEN:x-oauth-basic@github.com/$GITHUB_USER/$APP_CONF_REPO.git
           cd $APP_CONF_REPO
-          cp -r ../$APP_REPO/manifest/* .
+          cp -r ../$APP_REPO/manifests/* .
           git add -A
           git commit -m "first commit"
           # !!!Dice has setup already!!!
@@ -81,9 +82,9 @@ spec:
           export AWS_REGION=`aws configure get region`
           export KUBECONFIG=$TILE_HOME/kube.config
           aws eks update-kubeconfig --name $(self.inputs.prodClusterName) --region $AWS_REGION --role-arn $(self.inputs.prodMasterRoleARN) --kubeconfig $TILE_HOME/kube.config
-          kubectl create ns go-bumblebee
+          kubectl create ns go-bumblebee || true
           aws eks update-kubeconfig --name $(self.inputs.stageClusterName) --region $AWS_REGION --role-arn $(self.inputs.stageMasterRoleARN) --kubeconfig $TILE_HOME/kube.config
-          kubectl create ns go-bumblebee
+          kubectl create ns go-bumblebee || true
       - name: SetupDeploymentWithArgocd
         command: |
           cd $TILE_HOME/manifest/argocd
@@ -97,12 +98,12 @@ spec:
 
           # add staging deployment 
           sed -e 's/__github_repo__/'$githubRepo'/g' ./stage-all-in-one.json > ./stage-all-in-one-go.json
-          curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/applications -H "Authorization: Bearer $ARGOCD_TOKEN" -d "@stage-all-in-one.json"
+          curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/applications -H "Authorization: Bearer $ARGOCD_TOKEN" -d "@stage-all-in-one-go.json"
 
           # add production cluster
           kubectl apply -f ./argocd-remote.yaml
-          prodClusterArn=$(echo $(self.inputs.prodClusterArn) | sed -e "s#/#\\\/#g")
-          prodClusterEndpoint=$(echo $(self.inputs.prodClusterEndpoint) | sed -e "s#/#\\\/#g")
+          prodClusterArn=$(echo -n $(self.inputs.prodClusterArn) | sed -e "s#/#\\\/#g")
+          prodClusterEndpoint=$(echo -n $(self.inputs.prodClusterEndpoint) | sed -e "s#/#\\\/#g")
 
           sed -e 's/__caData__/$(self.inputs.prodClusterCertificateAuthorityData)/g' \
               -e 's/__name__/'$prodClusterArn'/g' \
