update: remove manifest from github:go-bumblebee

diff --git a/tiles-repo/go-bumblebee-jazz/0.7.1/tile-spec.yaml b/tiles-repo/go-bumblebee-jazz/0.7.1/tile-spec.yaml
--- a/tiles-repo/go-bumblebee-jazz/0.7.1/tile-spec.yaml
+++ b/tiles-repo/go-bumblebee-jazz/0.7.1/tile-spec.yaml
@@ -32,31 +32,36 @@ spec:
           curl -H "Authorization: token $GIT_ACCESS_TOKEN" --data '{"name":"'$APP_CONF_REPO'", "private": true}' https://api.github.com/user/repos
         readinessProbe:
           command: |
-            cat <<EOF > check.sh
-            #!/bin/bash
             retcode=`curl -s -o /dev/null -w "%{http_code}" https://github.com/$GITHUB_USER/$APP_CONF_REPO`
             if [ $retcode -ne 200 ]
             then
-              echo 'failed to create repo" >&2; exit 1
+              echo 'failed to create repo" >&2
               exit 1
             fi
-            EOF
-            chmod +x check.sh;./check.sh
           initialDelaySeconds: 5
           periodSeconds: 5
           timeoutSeconds: 30
           successThreshold: 1
           failureThreshold: 1
-      - name: SyncContentToRepository
+      - name: PrepareAppContent
+        command: |
+          cd $TILE_HOME
+          git clone https://github.com/$GITHUB_USER/$APP_REPO.git
+          cd $APP_REPO
+          git checkout $APP_BRANCH
+          git pull
+      - name: SyncAppContentToRepository
         command: |
           cd $TILE_HOME
           git clone https://$GIT_ACCESS_TOKEN:x-oauth-basic@github.com/$GITHUB_USER/$APP_CONF_REPO.git
           cd $APP_CONF_REPO
-          cp -r ../manifest/* .
+          cp -r ../$APP_REPO/manifest/* .
           git add -A
           git commit -m "first commit"
+          # !!!Dice has setup already!!!
           # git config --global user.email "robot@codebuild.aws"
           # git config --global user.name "robot"
+          # 
           git push
       - name: CreateSecrets
         command: |
